export const dummy = {

"dates":{"maximum":"2022-09-25", "minimum":"2022-08-08"},
"page":1,
"results":[
    {
    "adult":false,
    "backdrop_path":"/ybvm31ae8WW5O6411PDzwFlETuq.jpg",
    "genre_ids":[12,18,27],
    "id":760741,
    "original_language":"en",
    "original_title":"Beast",
    "overview":"두 딸 ‘메어’, ‘노라’와 함께 시간을 보내기 위해 친구 ‘마틴’이 있는 남아프리카를 찾은 의사 ‘네이트’.  그러나 즐거운 여행도 잠시, 처참히 죽어 있는 마을 사람들을 목격한 이들은 곧이어 이 모든 상황을 벌인 사자에게 맹목적으로 쫓기기 시작한다.  무전조차 터지지 않는 고립된 지역에서 마을을 완전히 장악해버린 사자로부터 벗어나기 위해 서로 의지하며 고군분투하는데…",
    "popularity":3689.282,
    "poster_path":"/xp6EOh0HEN4bx4ot8UfcYnUpT8U.jpg",
    "release_date":"2022-09-14",
    "title":"비스트",
    "video":false,
    "vote_average":7.1,
    "vote_count":473
    },
    {
    "adult":false,
    "backdrop_path":"/qaTzVAW1u16WFNsepjCrilBuInc.jpg",
    "genre_ids":[16,28,12],
    "id":539681,"original_language":"en",
    "original_title":"DC League of Super-Pets",
    "overview":"악당 렉스 루터의 계략으로 위험에 빠진 슈퍼맨을 비롯한 저스티스 리그의 슈퍼 히어로들을 구하기 위해 슈퍼독 크립토와 슈퍼 펫 친구들이 벌이는 파워 댕댕 모험을 그린 이야기",
    "popularity":1826.104,
    "poster_path":"/4L7hgezinra0QudLN8HPv8c3af1.jpg",
    "release_date":"2022-08-10",
    "title":"DC 리그 오브 슈퍼-펫",
    "video":false,
    "vote_average":7.5,
    "vote_count":638
    },
    {
    "adult":false,
    "backdrop_path":"/ugS5FVfCI3RV0ZwZtBV3HAV75OX.jpg",
    "genre_ids":[16,878,28],
    "id":610150,
    "original_language":"ja",
    "original_title":"ドラゴンボール超 スーパーヒーロー",
    "overview":"2018년에 개봉한 에 이은  시리즈의 두 번째 영화",
    "popularity":1963.513,
    "poster_path":"/uohymzBVaIYjbnoQstbnlia6ZPJ.jpg",
    "release_date":"2022-09-14",
    "title":"드래곤볼 슈퍼: 슈퍼 히어로",
    "video":false,
    "vote_average":8,
    "vote_count":1733
    },
    {
    "adult":false,
    "backdrop_path":"/AfvIjhDu9p64jKcmohS4hsPG95Q.jpg",
    "genre_ids":[27,53],
    "id":756999,
    "original_language":"en",
    "original_title":"The Black Phone",
    "overview":"사라진 아이들, 고장 난 전화기, 죽은 친구들과의 통화. 전화가 울리면 반드시 받을 것",
    "popularity":1301.968,
    "poster_path":"/eJPIkRiYGnvQaPCZtTRTDmhMJVK.jpg",
    "release_date":"2022-09-07",
    "title":"블랙폰",
    "video":false,
    "vote_average":7.9,
    "vote_count":2620
    },
    {
    "adult":false,
    "backdrop_path":"/rwgmDkIEv8VjAsWx25ottJrFvpO.jpg",
    "genre_ids":[10749,18],
    "id":744276,
    "original_language":"en",
    "original_title":"After Ever Happy",
    "overview":"뉴욕으로 떠난 테사와 소설가로 데뷔한 하딘,  런던에서 삶을 송두리째 뒤흔들 엄청난 과거를 알게 된 하딘은 자신의 불행 속에 테사를 끌어들이기 싫어서 애써 밀어낸다.  계속 제자리만 맴도는 관계에 지친 테사는 새로운 삶을 꿈꾸며 뉴욕으로 향하고, 떨어진 동안 그의 소중함을 깨달은 하딘은 뉴욕에서 테사와 재회하여 서로의 숨결과 살결을 탐한다.  다시 미래를 꿈꾸던 테사는 하딘이 집필한 소설 ‘애프터’에 자신의 첫 키스부터 첫 경험뿐만 아니라 감추고 싶던 아픈 기억까지 모두 담겨 있다는 것을 알고 충격을 받는데…",
    "popularity":1314.99,
    "poster_path":"/fZqvzsekRXxRrtEKIWoAWP5eqe7.jpg",
    "release_date":"2022-09-21",
    "title":"애프터: 에버 해피",
    "video":false,
    "vote_average":6.4,
    "vote_count":88
    },
    {
    "adult":false,
    "backdrop_path":"/xVbppM1xgbskOKgOuV8fbWBWHtt.jpg",
    "genre_ids":[27,9648,878,53],
    "id":762504,
    "original_language":"en",
    "original_title":"Nope",
    "overview":"거대하고, 주목받길 원하고, 미쳤다. 나쁜 기적이라는 것도 있을까?",
    "popularity":1007.783,
    "poster_path":"/52McjY2vAEiF0lJe8iBdOBNuyok.jpg",
    "release_date":"2022-08-17",
    "title":"놉","video":false,
    "vote_average":7,
    "vote_count":1588
    },
    {
    "adult":false,
    "backdrop_path":"/pdD47rPAYKVdPasoyhSAFPIFIWo.jpg",
    "genre_ids":[28,35,53],
    "id":718930,"original_language":"en",
    "original_title":"Bullet Train",
    "overview":"운이 없기로 유명한 킬러 레이디버그는 초고속 열차에 탑승해 의문의 서류 가방을 가져오라는 미션을 받는다. 생각보다 쉽게 미션을 클리어한 후 열차에서 내리려는 그를 가로막는 것이 있었으니,  그것은 바로 전세계에서 몰려든 초특급 킬러들! 열차에서 내릴 수 없다면 목숨을 걸고 가방을 지켜야만 한다. 과연 레이디버그는 무사히 열차에서 내려 미션을 완수할 수 있을까?","popularity":1055.774,
    "poster_path":"/msh4N8dxHk4FeEPZ8VBqHQFQYjI.jpg",
    "release_date":"2022-08-24",
    "title":"불릿 트레인",
    "video":false,
    "vote_average":7.4,
    "vote_count":893
    },
    {
    "adult":false,
    "backdrop_path":"/fqw8nJLPRgKRyFSDC0xBsC06NGC.jpg",
    "genre_ids":[28,12,14],
    "id":639933,
    "original_language":"en",
    "original_title":"The Northman",
    "overview":"10세기 아이슬란드, 숙부를 향한 '암레트' 왕자의 복수극을 그린 영화",
    "popularity":620.301,
    "poster_path":"/Aedz3vL7rC5fO0t7vQK7KUMwiW5.jpg",
    "release_date":"2022-08-31",
    "title":"노스맨",
    "video":false,
    "vote_average":7.2,"vote_count":2417
    },
    {
    "adult":false,
    "backdrop_path":"/fILWktCfh0ZiKWjWwyXalWzSvKX.jpg",
    "genre_ids":[18,35],
    "id":758330,
    "original_language":"en",
    "original_title":"Good Luck to You, Leo Grande",
    "overview":"단 한번도 섹스에 만족해 본 적 없는 인생 6*년차 낸시. 남편과 아이들이 떠나고, 은퇴 후 혼자 남은 그녀는 자신만의 은밀한 버킷리스트를 실행해보기로 결심한다  \"이끌리는 대로 다 잊고 당신만 생각해요” 외딴 호텔, 모든 게 자신 없는 '낸시' 앞에 젊고 매력적인 '리오 그랜드'가 나타나고, 처음 경험하는 퍼스널 서비스는 예상치 못한 해방감을 선사하는데...  올 여름, 뜨겁게 용감해지고 싶은 당신을 위한 굿 럭 무비!",
    "popularity":262.895,
    "poster_path":"/1ywjWmLHWHKAyOHGw0A3tcQclH0.jpg",
    "release_date":"2022-08-11",
    "title":"굿 럭 투 유, 리오 그랜드",
    "video":false,
    "vote_average":6.9,
    "vote_count":125
    },
    {
    "adult":false,
    "backdrop_path":"/k0bZfbtwZvMtKazaabeLVGQLhGg.jpg",
    "genre_ids":[80,18,53],
    "id":689700,
    "original_language":"en",
    "original_title":"Clean",
    "overview":"폭력으로 얼룩진 어두운 과거를 청산하고 쓰레기차를 모는 청소부로 조용한 삶을 보내고 있는 클린.\r 주인 없는 개를 돌보고, 버려진 집을 보수하며 속죄하듯 거리를 청소하는 그에게는\r 할머니와 단둘이 사는 이웃 소녀 디안다만이 유일한 친구다.  한편, 마약을 유통하며 경찰까지 좌지우지하는 갱단 보스 마이클의 아들 마이키의 출소 기념 파티에서\r 위험에 처한 디안다를 목격한 클린은 마이키와 패거리들을 엉망으로 만들고 디안다를 구해내는 데 성공한다.  마이클과 경찰 모두에게 쫓기는 신세가 된 클린은\r 마이클의 조직이 끝내 자신들을 찾아낼 것을 누구보다 잘 알기에 홀로 마을로 되돌아오고,\r 베일에 싸여 있던 그의 진짜 과거를 알게 된 마이클 역시 클린과의 마지막 싸움을 준비하는데…!",
    "popularity":258.41,
    "poster_path":"/gnWr71M3GhvVZs64UVMuvpdhHHb.jpg",
    "release_date":"2022-08-25",
    "title":"클린",
    "video":false,
    "vote_average":6.5,
    "vote_count":219
    },
    {
    "adult":false,
    "backdrop_path":"/mDvx0cafHm1Z0R295wMxzpVTGf9.jpg",
    "genre_ids":[12,16,35,10751,14],
    "id":676705,
    "original_language":"fr",
    "original_title":"Pil",
    "overview":"왕좌를 노리는 마법사 트리스탄을 막기 위해 필은 엉망진창 원정대를 이끌고 마법의 저주가 걸린 숲으로 모험을 떠나는데 어쩌다 시작된 필 공주와 일곱 기사들의 대환장 판타지 어드벤처!",
    "popularity":147.741,
    "poster_path":"/8Ju4ufMQT8WdCZHRF5ZdNg0Agk.jpg",
    "release_date":"2022-09-08",
    "title":"어쩌다 공주, 닭냥이 왕자를 부탁해!",
    "video":false,
    "vote_average":6.8,
    "vote_count":122
    },
    {
    "adult":false,
    "backdrop_path":"/jBIMZ0AlUYuFNsKbd4L6FojWMoy.jpg",
    "genre_ids":[16,35,10749],
    "id":820067,
    "original_language":"ja",
    "original_title":"映画 五等分の花嫁",
    "overview":"「낙제 직전」「공부가 싫은」미소녀 다섯 쌍둥이를\r 아르바이트 가정 교사로서 「졸업」까지 이끈 후타로.\r 배우에 전념하기 위해 휴학하기로 한 이치카의 공부를 봐주면서\r 「학교 축제」 준비에 힘쓰는 후타로와,\r 후회 없는 「학교 축제」를 만들기 위해 평소 이상으로 노력하는 요츠바.\r 어지러운 날들이 지나고 정신을 차려보니 「학교 축제」 전날.\r 후타로는 포기하지 않고 힘쓰는 이츠키의 모습에 힘입어,\r 니노의 각오와 미쿠의 결의, 그리고 이치카·요츠바·이츠키에 대한 마음의 답을 찾는다.\r 저마다의 생각을 안고 있는 와중,\r 드디어 시작된 고교 생활 최후의(마지막) 이벤트인 「학교 축제」 첫날.\r 『학교 축제 첫날 15시에 교실에 와줘』\r 교실에 모인 다섯 쌍둥이는, 후타로에게 어떠한 마음을 고백 받게 될까?",
    "popularity":64.741,
    "poster_path":"/63SDXxNKOA4ZfXvRCkF9B1y14Us.jpg",
    "release_date":"2022-09-22",
    "title":"극장판 5등분의 신부",
    "video":false,
    "vote_average":9.5,
    "vote_count":20
    },
    {
    "adult":false,
    "backdrop_path":"/gSsTGqZ7wT0uGhLDpcUOe1jYsi6.jpg",
    "genre_ids":[18,80,53],
    "id":660353,
    "original_language":"en",
    "original_title":"Ted K",
    "overview":"산속 작은 오두막에 은둔 생활을 하고 있는, 세상을 등진 천재 수학자 ‘존 카진스키’\r 산업화와 산림개발 등으로 자신의 오두막이 파괴되고 생계를 위협받자\r 세상에 대한 증오가 극에 달하고 무정부주의에 눈을 뜨면서 산업사회에 복수를 결심한다.\r 사제 폭발물 제조법을 독학으로 익혀 여러 차례 시험을 거친 후 세상을 바꿀 테러를 계획하게 되는데…",
    "popularity":38.861,
    "poster_path":"/ufGdX51Xi8X0QAS0I4vuvPjSnKx.jpg",
    "release_date":"2022-08-11",
    "title":"유나바머: 테드 K",
    "video":false,
    "vote_average":5.7,
    "vote_count":59
    },
    {
    "adult":false,
    "backdrop_path":"/2XQPcgGMyw2qSssv3CsCaOP61l3.jpg",
    "genre_ids":[53,10749,18,9648],
    "id":721625,
    "original_language":"en",
    "original_title":"Songbird",
    "overview":"감염병 스릴러 영화 송버드(Songbird)는 COVID-23 바이러스가 창궐하여 전 세계가 봉쇄된 지 4년이 지난 시점을 그리고 있습니다.  코비드-23이 전 세계를 휩쓴지 4년이 지난 시점에 수많은 사람들의 노력에도 불구하고 바이러스는 돌연변이를 일으키며 더 치명적으로 변해가고, 바이러스에 감염된 미국인들은 집에서 끌려나와 Q-Zones로 알려진 수용소에 강제 격리되는데 이 수용소에 들어가면 살아 돌아오기 힘듭니다.  자전거 택배 기사로 일하는 니코( KJ 아파)는 치명적인 병원체에 면역이지만 그의 연인 새라(소피아 카슨)는 병원체에 감염되어 수용소로 끌려갈 위기에 처하게 됩니다. 그러자 그는 불모지로 변한 로스앤젤레스 거리를 가로질러 전 세계를 휩쓴 팬데믹을 헤치고 그녀를 구하기 위한 모험을 감행합니다.","popularity":29.922,"poster_path":"/5jhrMIDfpeHECYGJzTXE4K8NQL1.jpg","release_date":"2022-08-17","title":"락다운 213주","video":false,"vote_average":6.1,"vote_count":571},{"adult":false,"backdrop_path":"/3DgGjoMjd188LN4v24Kw7iClKbT.jpg","genre_ids":[18],"id":660120,"original_language":"no","original_title":"Verdens verste menneske","overview":"의학을 공부하던 스물아홉 율리에는 자신이 진짜 원하는 걸 찾아 세상으로 나온다. 파티에서 만난 만화가 악셀과 사랑에 빠진 율리에, 하지만 삶의 다른 단계에서 만난 두 사람은 각자 다른 걸 원했고 조금씩 어긋난다. “내 삶에서 조연 역할을 하는 것 같아…” 율리에는 인생의 다음 챕터로 달려나간다.",
    "popularity":29.93,
    "poster_path":"/dpK3tNUsGEmrkKcmwsDMRt24cXW.jpg",
    "release_date":"2022-08-25",
    "title":"사랑할 땐 누구나 최악이 된다",
    "video":false,
    "vote_average":7.6,
    "vote_count":661
    },
    {
    "adult":false,
    "backdrop_path":"/g7KmJaGFvST5cyvA71V6epKAqIC.jpg",
    "genre_ids":[35,10402,10749,18],
    "id":872,"original_language":"en",
    "original_title":"Singin' in the Rain",
    "overview":"아마츄어 쇼 코미디언인 돈 록우드(진 켈리)와 코스모(도날드 오코너)는 공연을 하며 이곳저곳을 떠돌아다니다 뜻대로 되지않자 새 일자리를 얻기위해 헐리우드로 온다. 그런데 우연찮게 돈 록우드는 마뉴멘탈 영화사의 스턴트맨 역을 따내게 되고, 당시 최고의 인기를 누리고 있던 여배우인 리나 레이먼트(쟌 하겐)와 함께 다수의 영화에 출연함으로써 단연 스타로 급부상하게 된다. 그러나 화려한 영광도 잠시, 헐리웃 영화계가 무성영화에서 유성영화 체제로 전환됨으로써 목소리 연기가 너무나 형편없는 리나 레이먼트 때문에 영화를 완전히 망치게 되는데...",
    "popularity":22.31,
    "poster_path":"/7kfvd0Noh4VpdhNRSHc2zYpUlx8.jpg",
    "release_date":"1954-10-21",
    "title":"사랑은 비를 타고",
    "video":false,
    "vote_average":8.2,
    "vote_count":2516
    },
    {
    "adult":false,
    "backdrop_path":"/vC0tDDqSDY0ApO5qyzyGcGSM8jp.jpg",
    "genre_ids":[53,80,18],
    "id":939979,
    "original_language":"en",
    "original_title":"Paradise Highway",
    "overview":"감옥에 갇힌 동생의 목숨값을 위해 불법 화물을 밀반입하던 베테랑 트럭 드라이버 '샐리'(줄리엣 비노쉬)  갱단에게서 마지막 화물로 떠맡은 여자아이가 갑자기 의뢰인을 총으로 죽이면서 '샐리'는 일생일대의 기로에 서게 된다.  한편 이 사건을 추적하던 50년 차 FBI '게릭'(모건 프리먼)은 예상보다 더 거대한 범죄의 실체를 포착하는데…",
    "popularity":24.432,
    "poster_path":"/1n7qvqvwcXbcSZsCKOb7jGuw6Df.jpg",
    "release_date":"2022-08-24",
    "title":"파라다이스 하이웨이",
    "video":false,
    "vote_average":5.6,
    "vote_count":30
    },
    {
    "adult":false,
    "backdrop_path":"/aRJjCgp4uVUkXhDw8NClesQXbt3.jpg",
    "genre_ids":[53,28],
    "id":727340,
    "original_language":"ko",
    "original_title":"헌트",
    "overview":"북한 고위 관리가 망명을 요청한 이후, 안기부 해외팀 차장 박평호와 국내팀 차장 김정도는 동림으로 알려진 안기부 내 스파이, 남파간첩 총책임자를 밝혀내는 임무를 맡는다. 이윽고 동림이 국가 안보를 위태롭게 할 1급 비밀 정보를 누설하기 시작하고 안기부의 해외팀과 국내팀은 서로를 조사하기에 이른다. 당장 스파이를 밝혀내지 못하면 자신이 혐의를 받을 수 있는 일촉즉발의 상황에서 평호와 정도는 서서히 진실을 찾아내고, 마침내 대한민국 1호 암살 작전이라는 거대한 사건과 직면하게 되는데...",
    "popularity":18.082,
    "poster_path":"/zI0rMYcSUx16pHnsegWExPf1kDF.jpg",
    "release_date":"2022-08-10",
    "title":"헌트",
    "video":false,
    "vote_average":7.5,
    "vote_count":5
    },
    {
    "adult":false,
    "backdrop_path":"/eUl0JExl11ZyAgNjwxXzdIXlQlE.jpg",
    "genre_ids":[27,9648],
    "id":635,
    "original_language":"en",
    "original_title":"Angel Heart",
    "overview":"1955년, 어느 날 ‘사이퍼’라는 사람으로부터 사건 의뢰를 받은 뉴욕 사립 탐정 ‘해리 엔젤’.  세계2차대전 중 부상으로 식물인간이 되어 12년간 병원 생활을 하다 얼마 전 실종된 가수 자니 페이버릿을 찾는 일.  사건 조사는 12년간 그가 입원했던 병원에서부터 시작된다. 그러나 엔젤이 만난 사람들이 차례차례 시체로 발견되고 자니의 행적은 더욱 미묘해지는데… 충격과 공포의 오컬트 명작을 다시 만난다!","popularity":18.981,"poster_path":"/6qlfnohud4p1MjupJ20fotk3tgG.jpg","release_date":"1989-08-05","title":"엔젤 하트","video":false,"vote_average":7.1,"vote_count":1188},{"adult":false,"backdrop_path":"/xov3ufX4ZRyw2pSF3XLNjtvZPw4.jpg","genre_ids":[28,35],"id":736820,"original_language":"ko","original_title":"공조 2: 인터내셔날","overview":"남한으로 숨어든 글로벌 범죄 조직을 잡기 위해 새로운 공조 수사에 투입된 북한 형사 림철령. 수사 중의 실수로 사이버수사대로 전출됐던 남한 형사 강진태는 광수대 복귀를 위해 모두가 기피하는 철령의 파트너를 자청한다. 이렇게 다시 공조하게 된 철령과 진태! 철령과 재회한 민영의 마음도 불타오르는 가운데, 철령과 진태는 여전히 서로의 속내를 의심하면서도 나름 그럴싸한 공조 수사를 펼친다. 드디어 범죄 조직 리더인 장명준의 은신처를 찾아내려는 찰나, 미국에서 날아온 FBI 소속 잭이 그들 앞에 나타나는데…",
    "popularity":18.63,
    "poster_path":"/8FPbEnvnjMP7PoU63QQpV7IjMKU.jpg",
    "release_date":"2022-09-07",
    "title":"공조 2: 인터내셔날",
    "video":false,"vote_average":10,"vote_count":1}],
    "total_pages":4,"total_results":61}